name: Skyrim Inventory Management CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Create database
        run: bundle exec rails db:create
      - name: Migrate database
        run: bundle exec rails db:migrate
      - name: Run RSpec
        run: bundle exec rails spec
